name: hw-mquery
version: '0.1.0.2'
synopsis: Monadic query DSL
description: Please see README.md
category: Data
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2018 John Ky
license: BSD3
github: haskell-works/hw-mquery
homepage: http://github.com/haskell-works/hw-mquery#readme

extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
- base >=4 && <5
- lens

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -msse4.2
  exposed-modules:
  - HaskellWorks.Data.AtLeastSize
  - HaskellWorks.Data.Entry
  - HaskellWorks.Data.Micro
  - HaskellWorks.Data.Mini
  - HaskellWorks.Data.MQuery
  - HaskellWorks.Data.Row
  - HaskellWorks.Data.Shows
  - HaskellWorks.Data.ToBool
  dependencies:
  - ansi-wl-pprint
  - dlist

executables:
  hw-mquery-example:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -msse4.2
    dependencies:
    - hw-mquery

tests:
  hw-mquery-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - dlist
    - hedgehog
    - hspec
    - hw-hspec-hedgehog
    - hw-mquery
